spring.application.name=insighton-eureka

server.port=8761

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=insighton-eureka

spring.security.user.name=${USERNAME:testuser}
spring.security.user.password=${USERPASSWORD:testpassword}

management.endpoints.web.exposure.include=health