spring.application.name=insighton-eureka

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.security.user.name=${USERNAME:testuser}
spring.security.user.password=${USERPASSWORD:testpassword}

management.endpoints.web.exposure.include=health