name: eureka CI/CD

on:
  push:
    branches: [main, dev-deploy, dev]
  pull_request:
    branches: [main, dev-deploy, dev]

jobs:
  call-reusable:
    permissions:
      contents: read
      packages: write
    uses: nhnacademy-aiot3-insighton/InsightOn-infra/.github/workflows/eureka-ci-cd.yml@feature/ci-cd-deploy
    secrets: inherit